user nginx;

events {
    worker_connections 1000;
}
http {

    upstream authservices {
        server auth-service:8080;
    }

    upstream userservices {
        server user-service:8080;
    }

    upstream membershipservices{
        server membership-service:8080;
    }

    upstream trainerbookingservices {
        server trainerbooking-service:8080;
    }

    server {
            listen 4000;
           
            location /authservices/ {
                proxy_pass http://authservices/;
            }

            location /userservices/ {
                proxy_pass http://userservices/;
            }

            location /membershipservices/ {
                proxy_pass http://membershipservices/;
            }
            
            location /trainerbookingservices/ {
                proxy_pass http://trainerbookingservices/;
            }
            
    }
}