name: Build TrainerBookingService

on:
  push:
    branches: ["main"]

env:
  DOTNET_VERSION: 10.x
  API_PROJ_PATH: ./TrainerBookingService/TrainerBookingService.csproj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.API_PROJ_PATH }}

      - name: Build
        run: dotnet build ${{ env.API_PROJ_PATH }} --configuration Release --no-restore

        # 3. Setup Node (for Newman)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
        # 4. Install Newman globally
      - name: Install Newman
        run: npm install -g newman
      - name: Debug directory
        run: |
          pwd
          ls -la
      
      - name: Create Docker external network
        run: |
          docker network create fitlife

      - name: Setup Infrastructure
        run: |
          docker compose -f docker-compose.infrastructure.yml up -d --build
          docker compose -f docker-compose.infrastructure.yml ps
          sleep 30
      
      - name: Put secrets into vault ig
        run: |
          ./seed.vault.sh

      - name: Start services with Docker Compose
        run: |
          docker compose -f docker-compose.integration.yml up -d --build
          docker compose -f docker-compose.integration.yml ps
          sleep 30

      - name: Run Newman Tests
        run: |
          npm install -g newman
          newman run postman/PostmanCollection.json \
          --environment postman/PostmanEnvironment.json \
          --reporters cli,junit \
          --reporter-junit-export newman-report.xml
